---
title: "p8105_hw2_md4270"
author: "Manye Dong"
date: "2023-09-30"
output: github_document
---
```{r message=FALSE, results='hide'}
library(tidyverse)
library(readr)
```

## Problem 1
### clean pols_month dataset
```{r message=FALSE}
# clean snp dataset
pols_month = 
  read_csv("pols-month.csv") |>
  janitor::clean_names() |>
  separate(mon, sep = "-", into = c("year", "month", "day")) |>
  mutate(year = as.numeric(year), month = as.numeric(month), 
         day = as.numeric(day), month = month.name[month],
         president = ifelse(prez_gop==0, "dem", "gop")) |>
  select(-c(prez_dem, prez_gop, day))

head(pols_month)
```

### clean snp dataset
```{r message=FALSE}
snp = 
  read_csv("snp.csv") |>
  janitor::clean_names() |>
  separate(date, sep = "/", into = c("month", "day", "year")) |>
  mutate(year = as.numeric(year), month = as.numeric(month), 
         day = as.numeric(day), month = month.name[month], 
         year = ifelse((50<=year & year<100), 1900+year, 2000+year)) |>
  select(year, month, close)

head(snp)
```
### Clean Unemployment Dataset
```{r message=FALSE}
unemployment = 
  read_csv("unemployment.csv") |>
  janitor::clean_names() |>
  pivot_longer(
    jan:dec,
    names_to = "month", 
    values_to = "umployment_percent") |>
  mutate(year = as.numeric(year), 
         month = recode(month, 
                   "jan" = "January", 
                   "feb" = "February", 
                   "mar" = "March", 
                   "apr" = "April", 
                   "may" = "May", 
                   "jun" = "June", 
                   "jul" = "July", 
                   "aug" = "August", 
                   "sep" = "September", 
                   "oct" = "October", 
                   "nov" = "November", 
                   "dec" = "December"))

head(unemployment)
```
Write a short paragraph about these datasets. Explain briefly what each dataset contained, and describe the resulting dataset (e.g. give the dimension, range of years, and names of key variables).

## Problem 2
### Mr. Trash Wheel
